<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.25.0" />
      <PackageReference Include="Confluent.Kafka" Version="2.10.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.3" />
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SocialMedia.Application\SocialMedia.Application.csproj" />
      <ProjectReference Include="..\SocialMedia.Domain\SocialMedia.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Azure.Storage.Blobs"/>
    </ItemGroup>

</Project>
