<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Confluent.Kafka" Version="2.10.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SocialMedia.Application\SocialMedia.Application.csproj" />
      <ProjectReference Include="..\SocialMedia.Domain\SocialMedia.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Azure.Storage.Blobs">
        <HintPath>..\..\..\.nuget\packages\azure.storage.blobs\12.26.0-beta.1\lib\net8.0\Azure.Storage.Blobs.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
