name: CI Backend

env:
  DOTNET_VERSION: '9.x'
  SOLUTION_PATH: 'src/SocialMedia.sln'
  API_PROJECT_PATH: 'src/SocialMedia.API'

on: 
  push: 
    branches: 
      - develop
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build project
        run: dotnet build ${{ env.SOLUTION_PATH }}
